### PR TITLE
some packages add the `b` similar when using rc

### PR DESCRIPTION
**Pull request by cpanato**
*Issue #, if available:*

*Description of changes:*

Adding another suffixes, we have a few packages that use the format `x.y.x_bw` like https://github.com/Azure/azure-sdk-for-python/tree/azure-mgmt-servicefabricmanagedclusters_2.0.0b5

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]

**Comment by hectorj2f** [comment]
lgtm

**Comment by knqyf263** [comment]
Is there any documentation somewhere? The PR added `b` to both `preSuffixes` and `postSuffixes,` which confuses me.

**Comment by cpanato** [comment]
updates to only `preSuffixes` was my mistake.

which kind of documentation are you looking for?

**Comment by knqyf263** [comment]
I'm looking for a document about what `b` means as a pre-suffix. What about order compared to `alpha`, `beta`, etc? `(e.g. Is 1.2.3pre1` older than `1.2.3b1`?) Is `b` different from `beta`?

**Comment by cpanato** [comment]
> I'm looking for a document about what `b` means as a pre-suffix. What about order compared to `alpha`, `beta`, etc? `(e.g. Is 1.2.3pre1` older than `1.2.3b1`?) Is `b` different from `beta`?

that is something I cannot answer :( That specific project that I mentioned I did not find any docs for that.
if this makes no sense feel free to close
thanks!

**Comment by knqyf263** [comment]
Actually, I didn't find `b` even in apk-tools. I'm curious if `2.0.0b5` works with `apk`.
https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/acefa1acc1ce0e1871d17b4eafe4b1888f45d4d0/src/version.c#L73-74

Isn't it violating the apk version specification? I just want this library to comply with apk versioning.

**Comment by cpanato** [comment]
i think so, thanks! i will close this pr

**Comment by knqyf263** [comment]
If we confirm it should work with `apk`, we can reopen this PR. Thanks for your contribution.

**Comment by cpanato** [comment]
thank you!

**Pull request closed without merging**
